#template type
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: federatedmongodbreplicasets.mongodb.com
spec:
  group: mongodb.com
  names:
    kind: FederatedMongoDBReplicaSet
    plural: federatedmongodbreplicasets
    shortNames:
    - fmrs
  scope: Namespaced
  validation:
   openAPIV3Schema:
      properties:
        spec:
          properties:
            members:
              maximum: 50
              minimum: 1
              type: integer
            spec:
              properties:
                credentials:
                  type: string
                project:
                  type: string
                version:
                  type: string
          required:
          - credentials
          - project
          - version
          - members
  version: v1
---
# placement type
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: federatedmongodbreplicasetplacements.mongodb.com
spec:
  group: mongodb.com
  names:
    kind: FederatedMongoDBReplicaSetPlacement
    plural: federatedmongodbreplicasetplacements
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            clusterNames:
              items:
                type: string
              type: array
          type: object
        status:
          type: object
  version: v1
---
# override type
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: federatedmongodbreplicasetoverrides.mongodb.com
spec:
  group: mongodb.com
  names:
    kind: FederatedMongoDBReplicaSetOverride
    plural: federatedmongodbreplicasetoverrides
  scope: Namespaced
  validation:
   openAPIV3Schema:
      properties:
        spec:
          properties:
            overrides:
              items:
                properties:
                  clusterName:
                    type: string
                  members: 
                    format: int32
                    type: integer
  version: v1
